apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: db-secrets-sync
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-auth
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: db-secrets  # Nombre del secreto que generará automáticamente
    namespace: databases
    type: Opaque

---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: cloudflare-secret-sync
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-auth
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: cloudflare-api-token
    namespace: cert-manager
    type: Opaque

---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: redis-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-auth # El token que ya tienes configurado
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: redis-secret # Nombre del secreto real en K8s
    namespace: cache
    type: Opaque

---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: security-secrets-sync
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-auth
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: security-secrets
    namespace: security
    type: Opaque
