apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: security

data:
  users_database.yml: |
    users:
      admin:
        displayname: "Admin"
        password: "$argon2id$v=19$m=65536,t=3,p=4$nWGH2Fv9A6NgfEPMUPyyZw$Ze4m5US+BZq1ifLRai1jxgqAlFRfEj/TFocHmNPgiK4"
        email: francisco.heral02@gmail.com
        groups:
          - admins
