apiVersion: v1
kind: Service
metadata:
  name: authentik
  namespace: security
spec:
  type: ClusterIP
  selector:
    app: authentik
  ports:
    - name: http
      port: 9000
      targetPort: 9000
