apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik
  namespace: security
spec:
  replicas: 1

  selector:
    matchLabels:
      app: authentik

  template:
    metadata:
      labels:
        app: authentik

    spec:
      containers:
        - name: authentik
          image: ghcr.io/goauthentik/server:2026.2.3
          args:
            - server

          ports:
            - containerPort: 9000

          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: AUTHENTIK_SECRET_KEY

            - name: AUTHENTIK_HOST
              value: https://auth.devfheral.dev

            - name: AUTHENTIK_POSTGRESQL__HOST
              value: postgres-internal.databases.svc.cluster.local
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik_user
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: AUTHENTIK_POSTGRES_PASSWORD
                  
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: 9000
            initialDelaySeconds: 500
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 15
  
          readinessProbe:
            httpGet:
              path: /-/health/ready/
              port: 9000
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 10

        
