apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devfheral-internal-cert
  namespace: kube-system
spec:
  secretName: devfheral-internal-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.internal.devfheral.dev"
